### ISSUE TITLE
Check for MPT3 installation

### ISSUE THREAD

**Issue by bizzinho** [SPLIfA/CHIMMP#1]

**Comment by tillc** [comment]
check, I just had a first look, do you maybe have some sample CrystalData I can use?

**Comment by bizzinho** [comment]
I have just made a small change that allows you to run the GUI, given that MPT3 is installed.. I still think it would be best to talk briefly in skype so I can lead you through the information flow in the program

**Comment by tillc** [comment]
thanks, I installed the MPT3 and also have the neuronal networks toolbox. 

But another problem came up:
Undefined function or variable 'Polyhedron'.

Must be the function to plot the edge points?

**Comment by bizzinho** [comment]
Kinda

Please download the tbxmanager and run the following commands:

```
tbxmanager install mpt hysdel fourier cddmex lcp
tbxmanager restorepath
mpt_init
```

Also, download this file and add the folder to your matlab path
[qpc.zip](https://github.com/SPLIfA/CHIMMP/files/166862/qpc.zip)

This should get you going w.r.t. toolboxes

**Comment by tillc** [comment]
Great, thanks, I installed it again and the morphGui.m runs now without error messages. Looking forward to the Skype call tomorrow. 
(I struggled, because I have two different Matlab versions installed now, the academic licence (incl. the neuronal network toolbox) and the student licence.)

**Comment by bizzinho** [comment]
done
