### ISSUE TITLE
unitCell facetInfo data

### ISSUE THREAD

**Issue by tillc** [SPLIfA/CHIMMP#2]
Hi dave,
I haven't managed to get access to ADDICT yet, but Thomas requested the new version from Mike. I hope he will send us the new version soon. Do you maybe have an exemplary data set of the unitCell and facetInfo to run the interpretCrystallography.m file, that you could send me? I would like to automate reading and saving the crystal information...

**Comment by bizzinho** [comment]
Hey Till,

I was in holidays. I attach a zip file that contains a mat with info for a variety of compounds.

Please close this issue if this is what you wanted and it works.

[CrystalData.zip](https://github.com/SPLIfA/CHIMMP/files/254405/CrystalData.zip)

**Comment by bizzinho** [comment]
?
